<?php

require_once __DIR__ . '/vendor/autoload.php';

use Illuminate\Foundation\Application;
use Illuminate\Foundation\Configuration\Exceptions;
use Illuminate\Foundation\Configuration\Middleware;
use App\Models\Player;

$app = Application::configure(basePath: __DIR__)
    ->withRouting(
        web: __DIR__.'/routes/web.php',
        api: __DIR__.'/routes/api.php',
        commands: __DIR__.'/routes/console.php',
        health: '/up',
    )
    ->withMiddleware(function (Middleware $middleware) {
        //
    })
    ->withExceptions(function (Exceptions $exceptions) {
        //
    })->create();

$app->make(\Illuminate\Contracts\Console\Kernel::class)->bootstrap();

echo "Adding remaining Marvel Rivals players...\n";

// ENVY Players
$envyPlayers = [
    [
        'id' => 13,
        'name' => 'Window',
        'username' => 'Window',
        'real_name' => 'Window',
        'team_id' => 3,
        'role' => 'Vanguard',
        'main_hero' => 'Thor',
        'alt_heroes' => json_encode(['Captain America', 'Magneto', 'Hulk']),
        'region' => 'NA',
        'country' => 'United States',
        'rank' => 'Grand Master',
        'rating' => 2160.0,
        'age' => 24,
        'earnings' => 11200.00,
        'total_earnings' => 11200.00,
        'social_media' => json_encode(['twitter' => '@Window_fps', 'twitch' => 'window_fps']),
        'biography' => 'Veteran tank player and team captain known for strategic leadership.',
        'twitter' => '@Window_fps',
        'twitch' => 'window_fps',
        'team_position' => 'captain',
        'position_order' => 1,
    ],
    [
        'id' => 14,
        'name' => 'Shpeediry',
        'username' => 'Shpeediry',
        'real_name' => 'Shpeediry',
        'team_id' => 3,
        'role' => 'Duelist',
        'main_hero' => 'Spider-Man',
        'alt_heroes' => json_encode(['Iron Man', 'Black Widow', 'Hawkeye']),
        'region' => 'NA',
        'country' => 'United States',
        'rank' => 'Grand Master',
        'rating' => 2150.0,
        'age' => 25,
        'earnings' => 11200.00,
        'total_earnings' => 11200.00,
        'social_media' => json_encode(['twitter' => '@Shpeediry_', 'twitch' => 'shpeediry']),
        'biography' => 'High-speed DPS specialist with exceptional tracking and positioning.',
        'twitter' => '@Shpeediry_',
        'twitch' => 'shpeediry',
        'team_position' => 'player',
        'position_order' => 2,
    ],
    [
        'id' => 15,
        'name' => 'Coluge',
        'username' => 'Coluge',
        'real_name' => 'Colin Arai',
        'team_id' => 3,
        'role' => 'Vanguard',
        'main_hero' => 'Captain America',
        'alt_heroes' => json_encode(['Venom', 'Groot', 'Doctor Strange']),
        'region' => 'NA',
        'country' => 'United States',
        'rank' => 'Grand Master',
        'rating' => 2145.0,
        'age' => 25,
        'earnings' => 11200.00,
        'total_earnings' => 11200.00,
        'social_media' => json_encode(['twitter' => '@Coluge_ow', 'twitch' => 'coluge']),
        'biography' => 'Experienced tank player transitioning from Overwatch with strong fundamentals.',
        'twitter' => '@Coluge_ow',
        'twitch' => 'coluge',
        'team_position' => 'player',
        'position_order' => 3,
    ],
    [
        'id' => 16,
        'name' => 'nero',
        'username' => 'nero',
        'real_name' => 'nero',
        'team_id' => 3,
        'role' => 'Strategist',
        'main_hero' => 'Luna Snow',
        'alt_heroes' => json_encode(['Mantis', 'Rocket Raccoon', 'Jeff the Land Shark']),
        'region' => 'NA',
        'country' => 'United States',
        'rank' => 'Grand Master',
        'rating' => 2140.0,
        'age' => 26,
        'earnings' => 11200.00,
        'total_earnings' => 11200.00,
        'social_media' => json_encode(['twitter' => '@nero_gaming', 'twitch' => 'nero_gaming']),
        'biography' => 'Support specialist focused on team enablement and utility maximization.',
        'twitter' => '@nero_gaming',
        'twitch' => 'nero_gaming',
        'team_position' => 'player',
        'position_order' => 4,
    ],
    [
        'id' => 17,
        'name' => 'month',
        'username' => 'month',
        'real_name' => 'month',
        'team_id' => 3,
        'role' => 'Duelist',
        'main_hero' => 'Iron Man',
        'alt_heroes' => json_encode(['Punisher', 'Winter Soldier', 'Psylocke']),
        'region' => 'NA',
        'country' => 'United States',
        'rank' => 'Grand Master',
        'rating' => 2135.0,
        'age' => 27,
        'earnings' => 11200.00,
        'total_earnings' => 11200.00,
        'social_media' => json_encode(['twitter' => '@month_fps', 'twitch' => 'month_fps']),
        'biography' => 'Flexible DPS player capable of playing both hitscan and projectile heroes.',
        'twitter' => '@month_fps',
        'twitch' => 'month_fps',
        'team_position' => 'player',
        'position_order' => 5,
    ],
    [
        'id' => 18,
        'name' => 'cal',
        'username' => 'cal',
        'real_name' => 'cal',
        'team_id' => 3,
        'role' => 'Strategist',
        'main_hero' => 'Mantis',
        'alt_heroes' => json_encode(['Adam Warlock', 'Cloak & Dagger', 'Luna Snow']),
        'region' => 'NA',
        'country' => 'United States',
        'rank' => 'Grand Master',
        'rating' => 2130.0,
        'age' => 20,
        'earnings' => 11200.00,
        'total_earnings' => 11200.00,
        'social_media' => json_encode(['twitter' => '@cal_rivals', 'twitch' => 'cal_rivals']),
        'biography' => 'Young prodigy support player with exceptional mechanical skills for his age.',
        'twitter' => '@cal_rivals',
        'twitch' => 'cal_rivals',
        'team_position' => 'player',
        'position_order' => 6,
    ],
];

// FlyQuest Players
$flyquestPlayers = [
    [
        'id' => 19,
        'name' => 'FlyDPS1',
        'username' => 'FlyDPS1',
        'real_name' => 'TBA',
        'team_id' => 4,
        'role' => 'Duelist',
        'main_hero' => 'Spider-Man',
        'alt_heroes' => json_encode(['Iron Man', 'Hawkeye', 'Black Widow']),
        'region' => 'NA',
        'country' => 'United States',
        'rank' => 'Master',
        'rating' => 1980.0,
        'age' => 23,
        'earnings' => 4200.00,
        'total_earnings' => 4200.00,
        'social_media' => json_encode(['twitter' => '@flydps1', 'twitch' => 'flydps1']),
        'biography' => 'Newly acquired DPS player looking to prove himself in tier 1 competition.',
        'twitter' => '@flydps1',
        'twitch' => 'flydps1',
        'team_position' => 'captain',
        'position_order' => 1,
    ],
    [
        'id' => 20,
        'name' => 'FlyDPS2',
        'username' => 'FlyDPS2',
        'real_name' => 'TBA',
        'team_id' => 4,
        'role' => 'Duelist',
        'main_hero' => 'Iron Man',
        'alt_heroes' => json_encode(['Punisher', 'Winter Soldier', 'Psylocke']),
        'region' => 'NA',
        'country' => 'United States',
        'rank' => 'Master',
        'rating' => 1970.0,
        'age' => 24,
        'earnings' => 4200.00,
        'total_earnings' => 4200.00,
        'social_media' => json_encode(['twitter' => '@flydps2', 'twitch' => 'flydps2']),
        'biography' => 'Secondary DPS with focus on projectile heroes and flanking strategies.',
        'twitter' => '@flydps2',
        'twitch' => 'flydps2',
        'team_position' => 'player',
        'position_order' => 2,
    ],
    [
        'id' => 21,
        'name' => 'FlyTank1',
        'username' => 'FlyTank1',
        'real_name' => 'TBA',
        'team_id' => 4,
        'role' => 'Vanguard',
        'main_hero' => 'Captain America',
        'alt_heroes' => json_encode(['Thor', 'Magneto', 'Hulk']),
        'region' => 'NA',
        'country' => 'United States',
        'rank' => 'Master',
        'rating' => 1960.0,
        'age' => 25,
        'earnings' => 4200.00,
        'total_earnings' => 4200.00,
        'social_media' => json_encode(['twitter' => '@flytank1', 'twitch' => 'flytank1']),
        'biography' => 'Main tank player focused on creating space and enabling team strategies.',
        'twitter' => '@flytank1',
        'twitch' => 'flytank1',
        'team_position' => 'player',
        'position_order' => 3,
    ],
    [
        'id' => 22,
        'name' => 'FlyTank2',
        'username' => 'FlyTank2',
        'real_name' => 'TBA',
        'team_id' => 4,
        'role' => 'Vanguard',
        'main_hero' => 'Venom',
        'alt_heroes' => json_encode(['Groot', 'Doctor Strange', 'Thor']),
        'region' => 'NA',
        'country' => 'United States',
        'rank' => 'Master',
        'rating' => 1955.0,
        'age' => 26,
        'earnings' => 4200.00,
        'total_earnings' => 4200.00,
        'social_media' => json_encode(['twitter' => '@flytank2', 'twitch' => 'flytank2']),
        'biography' => 'Flexible tank player comfortable on both main tank and off-tank heroes.',
        'twitter' => '@flytank2',
        'twitch' => 'flytank2',
        'team_position' => 'player',
        'position_order' => 4,
    ],
    [
        'id' => 23,
        'name' => 'FlySupport1',
        'username' => 'FlySupport1',
        'real_name' => 'TBA',
        'team_id' => 4,
        'role' => 'Strategist',
        'main_hero' => 'Luna Snow',
        'alt_heroes' => json_encode(['Mantis', 'Rocket Raccoon', 'Jeff the Land Shark']),
        'region' => 'NA',
        'country' => 'United States',
        'rank' => 'Master',
        'rating' => 1950.0,
        'age' => 22,
        'earnings' => 4200.00,
        'total_earnings' => 4200.00,
        'social_media' => json_encode(['twitter' => '@flysupport1', 'twitch' => 'flysupport1']),
        'biography' => 'Main support player specializing in healing and team coordination.',
        'twitter' => '@flysupport1',
        'twitch' => 'flysupport1',
        'team_position' => 'player',
        'position_order' => 5,
    ],
    [
        'id' => 24,
        'name' => 'FlySupport2',
        'username' => 'FlySupport2',
        'real_name' => 'TBA',
        'team_id' => 4,
        'role' => 'Strategist',
        'main_hero' => 'Mantis',
        'alt_heroes' => json_encode(['Adam Warlock', 'Cloak & Dagger', 'Luna Snow']),
        'region' => 'NA',
        'country' => 'United States',
        'rank' => 'Master',
        'rating' => 1945.0,
        'age' => 23,
        'earnings' => 4200.00,
        'total_earnings' => 4200.00,
        'social_media' => json_encode(['twitter' => '@flysupport2', 'twitch' => 'flysupport2']),
        'biography' => 'Utility support player focused on enabling DPS and providing key cooldowns.',
        'twitter' => '@flysupport2',
        'twitch' => 'flysupport2',
        'team_position' => 'player',
        'position_order' => 6,
    ],
];

// NTMR Players
$ntmrPlayers = [
    [
        'id' => 25,
        'name' => 'NTMRDPS1',
        'username' => 'NTMRDPS1',
        'real_name' => 'TBA',
        'team_id' => 5,
        'role' => 'Duelist',
        'main_hero' => 'Spider-Man',
        'alt_heroes' => json_encode(['Iron Man', 'Black Widow', 'Hawkeye']),
        'region' => 'NA',
        'country' => 'United States',
        'rank' => 'Master',
        'rating' => 1940.0,
        'age' => 24,
        'earnings' => 7870.00,
        'total_earnings' => 7870.00,
        'social_media' => json_encode(['twitter' => '@ntmrdps1', 'twitch' => 'ntmrdps1']),
        'biography' => 'Replacement DPS player after original roster moved to Sentinels organization.',
        'twitter' => '@ntmrdps1',
        'twitch' => 'ntmrdps1',
        'team_position' => 'captain',
        'position_order' => 1,
    ],
    [
        'id' => 26,
        'name' => 'NTMRDPS2',
        'username' => 'NTMRDPS2',
        'real_name' => 'TBA',
        'team_id' => 5,
        'role' => 'Duelist',
        'main_hero' => 'Iron Man',
        'alt_heroes' => json_encode(['Punisher', 'Winter Soldier', 'Psylocke']),
        'region' => 'NA',
        'country' => 'United States',
        'rank' => 'Master',
        'rating' => 1935.0,
        'age' => 25,
        'earnings' => 7870.00,
        'total_earnings' => 7870.00,
        'social_media' => json_encode(['twitter' => '@ntmrdps2', 'twitch' => 'ntmrdps2']),
        'biography' => 'Secondary DPS bringing experience from tier 2 competitive scene.',
        'twitter' => '@ntmrdps2',
        'twitch' => 'ntmrdps2',
        'team_position' => 'player',
        'position_order' => 2,
    ],
    [
        'id' => 27,
        'name' => 'NTMRTank1',
        'username' => 'NTMRTank1',
        'real_name' => 'TBA',
        'team_id' => 5,
        'role' => 'Vanguard',
        'main_hero' => 'Thor',
        'alt_heroes' => json_encode(['Captain America', 'Magneto', 'Hulk']),
        'region' => 'NA',
        'country' => 'United States',
        'rank' => 'Master',
        'rating' => 1930.0,
        'age' => 26,
        'earnings' => 7870.00,
        'total_earnings' => 7870.00,
        'social_media' => json_encode(['twitter' => '@ntmrtank1', 'twitch' => 'ntmrtank1']),
        'biography' => 'Main tank player working to establish synergy with new roster.',
        'twitter' => '@ntmrtank1',
        'twitch' => 'ntmrtank1',
        'team_position' => 'player',
        'position_order' => 3,
    ],
    [
        'id' => 28,
        'name' => 'NTMRTank2',
        'username' => 'NTMRTank2',
        'real_name' => 'TBA',
        'team_id' => 5,
        'role' => 'Vanguard',
        'main_hero' => 'Captain America',
        'alt_heroes' => json_encode(['Venom', 'Groot', 'Doctor Strange']),
        'region' => 'NA',
        'country' => 'United States',
        'rank' => 'Master',
        'rating' => 1925.0,
        'age' => 27,
        'earnings' => 7870.00,
        'total_earnings' => 7870.00,
        'social_media' => json_encode(['twitter' => '@ntmrtank2', 'twitch' => 'ntmrtank2']),
        'biography' => 'Off-tank specialist focusing on peel and space denial for backline.',
        'twitter' => '@ntmrtank2',
        'twitch' => 'ntmrtank2',
        'team_position' => 'player',
        'position_order' => 4,
    ],
    [
        'id' => 29,
        'name' => 'NTMRSupport1',
        'username' => 'NTMRSupport1',
        'real_name' => 'TBA',
        'team_id' => 5,
        'role' => 'Strategist',
        'main_hero' => 'Luna Snow',
        'alt_heroes' => json_encode(['Mantis', 'Rocket Raccoon', 'Jeff the Land Shark']),
        'region' => 'NA',
        'country' => 'United States',
        'rank' => 'Master',
        'rating' => 1920.0,
        'age' => 23,
        'earnings' => 7870.00,
        'total_earnings' => 7870.00,
        'social_media' => json_encode(['twitter' => '@ntmrsupport1', 'twitch' => 'ntmrsupport1']),
        'biography' => 'Main support player adapting to new team environment and strategies.',
        'twitter' => '@ntmrsupport1',
        'twitch' => 'ntmrsupport1',
        'team_position' => 'player',
        'position_order' => 5,
    ],
    [
        'id' => 30,
        'name' => 'NTMRSupport2',
        'username' => 'NTMRSupport2',
        'real_name' => 'TBA',
        'team_id' => 5,
        'role' => 'Strategist',
        'main_hero' => 'Mantis',
        'alt_heroes' => json_encode(['Adam Warlock', 'Cloak & Dagger', 'Luna Snow']),
        'region' => 'NA',
        'country' => 'United States',
        'rank' => 'Master',
        'rating' => 1915.0,
        'age' => 24,
        'earnings' => 7870.00,
        'total_earnings' => 7870.00,
        'social_media' => json_encode(['twitter' => '@ntmrsupport2', 'twitch' => 'ntmrsupport2']),
        'biography' => 'Utility support focusing on team enablement and strategic cooldown usage.',
        'twitter' => '@ntmrsupport2',
        'twitch' => 'ntmrsupport2',
        'team_position' => 'player',
        'position_order' => 6,
    ],
];

// Combine all players
$allPlayers = array_merge($envyPlayers, $flyquestPlayers, $ntmrPlayers);

// Insert players
foreach ($allPlayers as $playerData) {
    Player::create($playerData);
    echo "Created player: {$playerData['name']} (Team: {$playerData['team_id']})\n";
}

echo "\nRemaining Marvel Rivals players imported successfully!\n";
echo "Total players now: " . Player::count() . "\n";

// Final verification
echo "\n=== FINAL VERIFICATION ===\n";
$teams = \App\Models\Team::with('players')->get();
foreach ($teams as $team) {
    echo "Team: {$team->name} ({$team->short_name}) - {$team->players->count()}/6 players\n";
    if ($team->players->count() > 0) {
        echo "  Players: " . $team->players->pluck('name')->implode(', ') . "\n";
        echo "  Roles: " . $team->players->pluck('role')->unique()->implode(', ') . "\n";
    }
    echo "\n";
}