<?php

require_once __DIR__ . '/vendor/autoload.php';

use Illuminate\Foundation\Application;
use Illuminate\Foundation\Configuration\Exceptions;
use Illuminate\Foundation\Configuration\Middleware;
use App\Models\Team;
use App\Models\Player;

$app = Application::configure(basePath: __DIR__)
    ->withRouting(
        web: __DIR__.'/routes/web.php',
        api: __DIR__.'/routes/api.php',
        commands: __DIR__.'/routes/console.php',
        health: '/up',
    )
    ->withMiddleware(function (Middleware $middleware) {
        //
    })
    ->withExceptions(function (Exceptions $exceptions) {
        //
    })->create();

$app->make(\Illuminate\Contracts\Console\Kernel::class)->bootstrap();

echo "Starting Marvel Rivals data import...\n";

// Clear existing data safely
\DB::statement('SET FOREIGN_KEY_CHECKS=0;');
Player::truncate();
Team::truncate();
\DB::statement('SET FOREIGN_KEY_CHECKS=1;');
echo "Cleared existing data.\n";

// Team data
$teams = [
    [
        'id' => 1,
        'name' => '100 Thieves',
        'short_name' => '100T',
        'logo' => '100t-logo.png',
        'region' => 'NA',
        'country' => 'United States',
        'flag' => 'us',
        'rating' => 2150,
        'rank' => 1,
        'win_rate' => 85.5,
        'points' => 2800,
        'record' => '34-6',
        'peak' => 2200,
        'streak' => 'W12',
        'last_match' => '2025-01-15',
        'founded' => '2017',
        'captain' => 'delenna',
        'coach' => 'iRemiix & Malenia',
        'website' => 'https://100thieves.com',
        'earnings' => 50000.00,
        'social_media' => json_encode([
            'twitter' => '@100Thieves',
            'instagram' => '@100thieves',
            'youtube' => '100Thieves',
            'discord' => '100thieves'
        ]),
        'achievements' => json_encode([
            'tournaments_won' => 8,
            'major_titles' => ['MRVL Championship 2024', 'NA Invitational 2024'],
            'prize_money' => '$50,000+'
        ]),
        'twitter' => '@100Thieves',
        'instagram' => '@100thieves',
        'youtube' => '100Thieves',
        'twitch' => 'https://twitch.tv/100thieves',
        'tiktok' => '@100thieves_',
        'discord' => 'https://discord.gg/100thieves',
        'facebook' => 'https://facebook.com/100Thieves',
        'founded_date' => '2017-04-06',
        'owner' => 'Matthew Haag',
    ],
    [
        'id' => 2,
        'name' => 'Sentinels',
        'short_name' => 'SEN',
        'logo' => 'sentinels-logo.png',
        'region' => 'NA',
        'country' => 'United States',
        'flag' => 'us',
        'rating' => 2100,
        'rank' => 2,
        'win_rate' => 82.3,
        'points' => 2650,
        'record' => '31-8',
        'peak' => 2180,
        'streak' => 'W8',
        'last_match' => '2025-01-14',
        'founded' => '2018',
        'captain' => 'Rymazing',
        'coach' => 'Crimzo',
        'website' => 'https://sentinels.gg',
        'earnings' => 30000.00,
        'social_media' => json_encode([
            'twitter' => '@Sentinels',
            'instagram' => '@sentinelsgg',
            'youtube' => 'SentinelsGG',
            'discord' => 'sentinels'
        ]),
        'achievements' => json_encode([
            'tournaments_won' => 6,
            'major_titles' => ['Spring Masters 2024', 'Regional Championship 2024'],
            'prize_money' => '$30,000+'
        ]),
        'twitter' => '@Sentinels',
        'instagram' => '@sentinelsgg',
        'youtube' => 'SentinelsGG',
        'twitch' => 'https://twitch.tv/sentinels',
        'tiktok' => '@sentinelsgg',
        'discord' => 'https://discord.gg/sentinels',
        'facebook' => 'https://facebook.com/SentinelsGG',
        'founded_date' => '2018-01-01',
        'owner' => 'Rob Moore',
    ],
    [
        'id' => 3,
        'name' => 'ENVY',
        'short_name' => 'NV',
        'logo' => 'envy-logo.png',
        'region' => 'NA',
        'country' => 'United States',
        'flag' => 'us',
        'rating' => 2080,
        'rank' => 3,
        'win_rate' => 79.2,
        'points' => 2500,
        'record' => '28-12',
        'peak' => 2120,
        'streak' => 'L1',
        'last_match' => '2025-01-13',
        'founded' => '2017',
        'captain' => 'Window',
        'coach' => 'Gator',
        'website' => 'https://envy.gg',
        'earnings' => 67000.00,
        'social_media' => json_encode([
            'twitter' => '@Envy',
            'instagram' => '@envy',
            'youtube' => 'Envy',
            'discord' => 'envy'
        ]),
        'achievements' => json_encode([
            'tournaments_won' => 4,
            'major_titles' => ['Summer Circuit 2024'],
            'prize_money' => '$67,000'
        ]),
        'twitter' => '@Envy',
        'instagram' => '@envy',
        'youtube' => 'Envy',
        'twitch' => 'https://twitch.tv/envy',
        'tiktok' => '@envy',
        'discord' => 'https://discord.gg/envy',
        'facebook' => 'https://facebook.com/Envy',
        'founded_date' => '2017-08-15',
        'owner' => 'Mike Rufail',
    ],
    [
        'id' => 4,
        'name' => 'FlyQuest',
        'short_name' => 'FLY',
        'logo' => 'flyquest-logo.png',
        'region' => 'NA',
        'country' => 'United States',
        'flag' => 'us',
        'rating' => 1950,
        'rank' => 4,
        'win_rate' => 72.8,
        'points' => 2200,
        'record' => '22-18',
        'peak' => 2000,
        'streak' => 'W3',
        'last_match' => '2025-01-12',
        'founded' => '2017',
        'captain' => 'TBD',
        'coach' => 'TBD',
        'website' => 'https://flyquest.gg',
        'earnings' => 25000.00,
        'social_media' => json_encode([
            'twitter' => '@FlyQuest',
            'instagram' => '@flyquest',
            'youtube' => 'FlyQuest',
            'discord' => 'flyquest'
        ]),
        'achievements' => json_encode([
            'tournaments_won' => 2,
            'major_titles' => ['Qualifier Championship 2024'],
            'prize_money' => '$25,000+'
        ]),
        'twitter' => '@FlyQuest',
        'instagram' => '@flyquest',
        'youtube' => 'FlyQuest',
        'twitch' => 'https://twitch.tv/flyquest',
        'tiktok' => '@flyquest',
        'discord' => 'https://discord.gg/flyquest',
        'facebook' => 'https://facebook.com/FlyQuest',
        'founded_date' => '2017-02-01',
        'owner' => 'Tristan Sommer',
    ],
    [
        'id' => 5,
        'name' => 'NTMR',
        'short_name' => 'NTMR',
        'logo' => 'ntmr-logo.png',
        'region' => 'NA',
        'country' => 'United States',
        'flag' => 'us',
        'rating' => 1920,
        'rank' => 5,
        'win_rate' => 68.5,
        'points' => 2050,
        'record' => '19-21',
        'peak' => 1980,
        'streak' => 'L2',
        'last_match' => '2025-01-11',
        'founded' => '2024',
        'captain' => 'TBD',
        'coach' => 'AdaLynx',
        'website' => 'https://ntmr.gg',
        'earnings' => 47200.00,
        'social_media' => json_encode([
            'twitter' => '@NTMResports',
            'instagram' => '@ntmr_esports',
            'youtube' => 'NTMR',
            'discord' => 'ntmr'
        ]),
        'achievements' => json_encode([
            'tournaments_won' => 1,
            'major_titles' => [],
            'prize_money' => '$47,200'
        ]),
        'twitter' => '@NTMResports',
        'instagram' => '@ntmr_esports',
        'youtube' => 'NTMR',
        'twitch' => 'https://twitch.tv/ntmr',
        'tiktok' => '@ntmr_esports',
        'discord' => 'https://discord.gg/ntmr',
        'facebook' => 'https://facebook.com/NTMResports',
        'founded_date' => '2024-01-01',
        'owner' => 'Private',
    ],
];

// Insert teams
foreach ($teams as $teamData) {
    Team::create($teamData);
    echo "Created team: {$teamData['name']}\n";
}

// Player data
$players = [
    // 100 Thieves Players
    [
        'id' => 1,
        'name' => 'delenna',
        'username' => 'delenna',
        'real_name' => 'Anthony Rosa',
        'team_id' => 1,
        'role' => 'Duelist',
        'main_hero' => 'Spider-Man',
        'alt_heroes' => json_encode(['Iron Man', 'Star-Lord', 'Punisher']),
        'region' => 'NA',
        'country' => 'United States',
        'rank' => 'Grand Master',
        'rating' => 2180.0,
        'age' => 24,
        'earnings' => 8500.00,
        'total_earnings' => 8500.00,
        'social_media' => json_encode(['twitter' => '@delenna_ow', 'twitch' => 'delenna']),
        'biography' => 'Veteran FPS player transitioning to Marvel Rivals with exceptional aim and game sense.',
        'twitter' => '@delenna_ow',
        'twitch' => 'delenna',
        'team_position' => 'captain',
        'position_order' => 1,
    ],
    [
        'id' => 2,
        'name' => 'hxrvey',
        'username' => 'hxrvey',
        'real_name' => 'Harvey Scattergood',
        'team_id' => 1,
        'role' => 'Vanguard',
        'main_hero' => 'Captain America',
        'alt_heroes' => json_encode(['Thor', 'Hulk', 'Venom']),
        'region' => 'NA',
        'country' => 'United Kingdom',
        'rank' => 'Grand Master',
        'rating' => 2160.0,
        'age' => 22,
        'earnings' => 8500.00,
        'total_earnings' => 8500.00,
        'social_media' => json_encode(['twitter' => '@hxrvey_', 'twitch' => 'hxrvey']),
        'biography' => 'UK import known for aggressive tank play and shotcalling abilities.',
        'twitter' => '@hxrvey_',
        'twitch' => 'hxrvey',
        'team_position' => 'player',
        'position_order' => 2,
    ],
    [
        'id' => 3,
        'name' => 'SJP',
        'username' => 'SJP',
        'real_name' => 'James Hudson',
        'team_id' => 1,
        'role' => 'Strategist',
        'main_hero' => 'Luna Snow',
        'alt_heroes' => json_encode(['Mantis', 'Jeff the Land Shark', 'Rocket Raccoon']),
        'region' => 'NA',
        'country' => 'United States',
        'rank' => 'Grand Master',
        'rating' => 2150.0,
        'age' => 26,
        'earnings' => 8500.00,
        'total_earnings' => 8500.00,
        'social_media' => json_encode(['twitter' => '@SJP_gg', 'twitch' => 'sjp_gg']),
        'biography' => 'Support specialist with excellent positioning and team coordination skills.',
        'twitter' => '@SJP_gg',
        'twitch' => 'sjp_gg',
        'team_position' => 'player',
        'position_order' => 3,
    ],
    [
        'id' => 4,
        'name' => 'Terra',
        'username' => 'Terra',
        'real_name' => 'Marschal Weaver',
        'team_id' => 1,
        'role' => 'Duelist',
        'main_hero' => 'Iron Man',
        'alt_heroes' => json_encode(['Black Widow', 'Hawkeye', 'Winter Soldier']),
        'region' => 'NA',
        'country' => 'United States',
        'rank' => 'Grand Master',
        'rating' => 2170.0,
        'age' => 23,
        'earnings' => 8500.00,
        'total_earnings' => 8500.00,
        'social_media' => json_encode(['twitter' => '@Terra_fps', 'twitch' => 'terra_fps']),
        'biography' => 'Flexible DPS player capable of adapting to any team composition needs.',
        'twitter' => '@Terra_fps',
        'twitch' => 'terra_fps',
        'team_position' => 'player',
        'position_order' => 4,
    ],
    [
        'id' => 5,
        'name' => 'TTK',
        'username' => 'TTK',
        'real_name' => 'Eric Arraiga',
        'team_id' => 1,
        'role' => 'Vanguard',
        'main_hero' => 'Thor',
        'alt_heroes' => json_encode(['Magneto', 'Doctor Strange', 'Groot']),
        'region' => 'NA',
        'country' => 'United States',
        'rank' => 'Grand Master',
        'rating' => 2140.0,
        'age' => 25,
        'earnings' => 8500.00,
        'total_earnings' => 8500.00,
        'social_media' => json_encode(['twitter' => '@TTK_gaming', 'twitch' => 'ttk_gaming']),
        'biography' => 'Versatile tank player with deep understanding of space creation and peel.',
        'twitter' => '@TTK_gaming',
        'twitch' => 'ttk_gaming',
        'team_position' => 'player',
        'position_order' => 5,
    ],
    [
        'id' => 6,
        'name' => 'Vinnie',
        'username' => 'Vinnie',
        'real_name' => 'Vincent Scaratine',
        'team_id' => 1,
        'role' => 'Strategist',
        'main_hero' => 'Mantis',
        'alt_heroes' => json_encode(['Adam Warlock', 'Cloak & Dagger', 'Luna Snow']),
        'region' => 'NA',
        'country' => 'United States',
        'rank' => 'Grand Master',
        'rating' => 2135.0,
        'age' => 27,
        'earnings' => 8500.00,
        'total_earnings' => 8500.00,
        'social_media' => json_encode(['twitter' => '@Vinnie_val', 'twitch' => 'vinnie_val']),
        'biography' => 'Experienced support player with exceptional game sense and clutch factor.',
        'twitter' => '@Vinnie_val',
        'twitch' => 'vinnie_val',
        'team_position' => 'player',
        'position_order' => 6,
    ],
    // Sentinels Players
    [
        'id' => 7,
        'name' => 'Rymazing',
        'username' => 'Rymazing',
        'real_name' => 'Ryan Bishop',
        'team_id' => 2,
        'role' => 'Duelist',
        'main_hero' => 'Spider-Man',
        'alt_heroes' => json_encode(['Iron Man', 'Hawkeye', 'Psylocke']),
        'region' => 'NA',
        'country' => 'United States',
        'rank' => 'Grand Master',
        'rating' => 2170.0,
        'age' => 25,
        'earnings' => 5000.00,
        'total_earnings' => 5000.00,
        'social_media' => json_encode(['twitter' => '@Rymazing_', 'twitch' => 'rymazing']),
        'biography' => 'Aggressive entry fragger with exceptional mechanical skills and game awareness.',
        'twitter' => '@Rymazing_',
        'twitch' => 'rymazing',
        'team_position' => 'captain',
        'position_order' => 1,
    ],
    [
        'id' => 8,
        'name' => 'SuperGomez',
        'username' => 'SuperGomez',
        'real_name' => 'Anthony Gomez',
        'team_id' => 2,
        'role' => 'Duelist',
        'main_hero' => 'Iron Man',
        'alt_heroes' => json_encode(['Black Widow', 'Punisher', 'Winter Soldier']),
        'region' => 'NA',
        'country' => 'United States',
        'rank' => 'Grand Master',
        'rating' => 2155.0,
        'age' => 28,
        'earnings' => 5000.00,
        'total_earnings' => 5000.00,
        'social_media' => json_encode(['twitter' => '@SuperGomez_gg', 'twitch' => 'supergomez']),
        'biography' => 'Consistent DPS player known for clutch performances in high-pressure situations.',
        'twitter' => '@SuperGomez_gg',
        'twitch' => 'supergomez',
        'team_position' => 'player',
        'position_order' => 2,
    ],
    [
        'id' => 9,
        'name' => 'aramori',
        'username' => 'aramori',
        'real_name' => 'Chassidy Kaye',
        'team_id' => 2,
        'role' => 'Strategist',
        'main_hero' => 'Luna Snow',
        'alt_heroes' => json_encode(['Mantis', 'Rocket Raccoon', 'Jeff the Land Shark']),
        'region' => 'NA',
        'country' => 'United States',
        'rank' => 'Grand Master',
        'rating' => 2145.0,
        'age' => 23,
        'earnings' => 5000.00,
        'total_earnings' => 5000.00,
        'social_media' => json_encode(['twitter' => '@aramori_gg', 'twitch' => 'aramori']),
        'biography' => 'Rising support star with exceptional positioning and team coordination.',
        'twitter' => '@aramori_gg',
        'twitch' => 'aramori',
        'team_position' => 'player',
        'position_order' => 3,
    ],
    [
        'id' => 10,
        'name' => 'Karova',
        'username' => 'Karova',
        'real_name' => 'Mark Kvashin',
        'team_id' => 2,
        'role' => 'Strategist',
        'main_hero' => 'Mantis',
        'alt_heroes' => json_encode(['Adam Warlock', 'Cloak & Dagger', 'Luna Snow']),
        'region' => 'NA',
        'country' => 'Russia',
        'rank' => 'Grand Master',
        'rating' => 2150.0,
        'age' => 26,
        'earnings' => 5000.00,
        'total_earnings' => 5000.00,
        'social_media' => json_encode(['twitter' => '@Karova_fps', 'twitch' => 'karova_fps']),
        'biography' => 'International support player bringing EU experience to NA competition.',
        'twitter' => '@Karova_fps',
        'twitch' => 'karova_fps',
        'team_position' => 'player',
        'position_order' => 4,
    ],
    [
        'id' => 11,
        'name' => 'Hogz',
        'username' => 'Hogz',
        'real_name' => 'Zairek Poll',
        'team_id' => 2,
        'role' => 'Vanguard',
        'main_hero' => 'Captain America',
        'alt_heroes' => json_encode(['Thor', 'Magneto', 'Venom']),
        'region' => 'NA',
        'country' => 'United States',
        'rank' => 'Grand Master',
        'rating' => 2140.0,
        'age' => 24,
        'earnings' => 5000.00,
        'total_earnings' => 5000.00,
        'social_media' => json_encode(['twitter' => '@Hogz_gaming', 'twitch' => 'hogz_gaming']),
        'biography' => 'Aggressive tank player specializing in space creation and initiation.',
        'twitter' => '@Hogz_gaming',
        'twitch' => 'hogz_gaming',
        'team_position' => 'player',
        'position_order' => 5,
    ],
    [
        'id' => 12,
        'name' => 'TempSix',
        'username' => 'TempSix',
        'real_name' => 'Temporary Player',
        'team_id' => 2,
        'role' => 'Vanguard',
        'main_hero' => 'Hulk',
        'alt_heroes' => json_encode(['Groot', 'Doctor Strange', 'Thor']),
        'region' => 'NA',
        'country' => 'United States',
        'rank' => 'Master',
        'rating' => 2000.0,
        'age' => 22,
        'earnings' => 5000.00,
        'total_earnings' => 5000.00,
        'social_media' => json_encode(['twitter' => '@temp6_gg', 'twitch' => 'temp6']),
        'biography' => 'Substitute player filling roster requirements while permanent member is sought.',
        'twitter' => '@temp6_gg',
        'twitch' => 'temp6',
        'team_position' => 'sub',
        'position_order' => 6,
    ],
];

// Insert players
foreach ($players as $playerData) {
    Player::create($playerData);
    echo "Created player: {$playerData['name']} (Team: {$playerData['team_id']})\n";
}

echo "\nMarvel Rivals data import completed successfully!\n";
echo "Teams created: " . Team::count() . "\n";
echo "Players created: " . Player::count() . "\n";

// Verify data
echo "\n=== VERIFICATION ===\n";
$teams = Team::with('players')->get();
foreach ($teams as $team) {
    echo "Team: {$team->name} ({$team->short_name})\n";
    echo "  Region: {$team->region}, Country: {$team->country}\n";
    echo "  Rating: {$team->rating}, Rank: {$team->rank}\n";
    echo "  Earnings: $" . number_format($team->earnings, 2) . "\n";
    echo "  Players ({$team->players->count()}): ";
    echo $team->players->pluck('name')->implode(', ') . "\n";
    echo "  Roles: " . $team->players->pluck('role')->unique()->implode(', ') . "\n";
    echo "\n";
}